# Generated by Django 4.1.5 on 2023-01-16 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('date_created', models.TimeField(auto_now_add=True)),
                ('movie_file', models.FileField(upload_to='movies/')),
                ('movie_thumbnail', models.ImageField(upload_to='thumbnail/')),
                ('watch_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flix.category')),
            ],
        ),
    ]
